### PR TITLE
ENH: fix coveralls.io

### PR DESCRIPTION
**Pull request by themperek**
Sorry, the commits are mess but you can squash them during merge.

### CODE REVIEW

**Comment by themperek** [comment]
It seems to be OK for my fork: 
https://travis-ci.org/themperek/testbeam_analysis
https://coveralls.io/builds/9688624

Has issues here.

**Comment by DavidLP** [comment]
You know why it stopped working? I have the nosetest/coveralls setup for all my project and did not have an issue yet.

**Comment by DavidLP** [comment]
But I also prefer `pytest` over `nosetest`

**Comment by themperek** [comment]
I looks to me development brunch is just broken at the moment.  Have no idea why it has an issue. It looks like problem is the storage of the coverage data and with pytest it can be controlled.

**Comment by DavidLP** [comment]
> It looks like problem is the storage of the coverage data and with pytest it can be controlled.

Yea. Its weird. But whatever, I merge.

**Comment by themperek** [comment]
PS. You can **squash** commits from PR during merge.

**Comment by laborleben** [comment]
To be more precise:
Do an interactive rebase on the feature branch and do a no-ff merge of the feature branch into development.

**Comment by themperek** [comment]
Or use the a button on github.com PR page.

**Comment by laborleben** [comment]
Never tested that, and I don't know if it will do a no-ff merge after rebase.

**Pull request merged**
