### PR TITLE
Gui

### PR DESCRIPTION
**Pull request by leloup314**

### CODE REVIEW

**Comment by leloup314** [comment]
@DavidLP Why are there so many conflicting files? :sweat_smile: Shouldn't files only have a conflict if they had been changed after the last merge in the respective branch?

**Comment by DavidLP** [comment]
I guess so ;-). Did you force push? Nothing you cannot fix with a `rebase`. Can you try?

**Comment by DavidLP** [comment]
I think the issue is that this is merged now to development and thus this has to be rebased.

**Comment by DavidLP** [comment]
Lets rebase and then create a new PR

**Comment by leloup314** [comment]
I don't think that I force pushed. Okay, let's rebase!

**Pull request closed without merging**
