### PR TITLE
Data hosting

### PR DESCRIPTION
**Pull request by DavidLP**
The amount of data needed for unit tests and the examples makes the git project unnecessary large (#55). Also in view of a `PyPI` release this had to be fixed.
Therefore all unit tests fixtures and examples data are now loaded on the fly from an [ownCloud](https://owncloud.org/) service called [sciebo](https://www.sciebo.de/) that is hosted by several universities in Germany. The data is in a public folder, write access can be given on demand.
The disadvantage is that other branches with different test data need the data also hosted there.
I still think that is the best solution for now and we should use the additional storage for some more demanding MIMOSA+FEI4 telescope examples.

### CODE REVIEW

**Comment by laborleben** [comment]
That was quite a bit of work :-) I let CI finish the job and then sign off.

**Comment by DavidLP** [comment]
Yes ;-) Especially since I implemented another cloud service that we do not use now... Nevertheless most changes are in the unittests, productive code is untouched,

**Review by laborleben — APPROVED** [review]

**Comment by themperek** [comment]
Maybe use release folder of github?

https://help.github.com/articles/about-releases/

**Comment by themperek** [comment]
Maybe use release folder of github?

https://help.github.com/articles/about-releases/

**Comment by DavidLP** [comment]
@themperek That might be a good idea for releases! I do not see how this helps us for development

**Comment by themperek** [comment]
Can keep some versioning that will hold across branches and history.

**Comment by DavidLP** [comment]
I also do not like do have no versioning for the test files now. But we still implement features too frequently that dumping (often changing) binary data in (not existing) releases would help now.

**Comment by laborleben** [comment]
You have a hash value that points you to the right test data. In my opinion this cannot be better. It is just consuming lots of space after some time when the files are updated frequently.
If you go back in time and you will always find the proper test data? Do I get this right?

**Comment by DavidLP** [comment]
You mean if `sciebo` does this? I do not think that it works like this. A public folder is nothing else than a not easy to guess link. The link is the secret. If the data changes the link should stay the same.

**Comment by laborleben** [comment]
Not easy to guess link -> some hash/random value. This is exactly what I meant.

OK, but this is bad. Any possibility to keep the old files available for downloading? Otherwise we cannot go back in time and run the tests. Not that I want to go back in time ;-)

**Comment by DavidLP** [comment]
>  Any possibility to keep the old files available for downloading?

Well, I could just never delete them...

Until we have releases and we add the data to the release I think that is ok.
Downloading data from github can be done without changing to much code.

Let go into the future and forget the past :-;

**Pull request merged**
