### PR TITLE
ENH: fix path not dependent on current working directory

### PR DESCRIPTION
**Pull request by laborleben**
This is fixing the paths to the modules and fixtures and fixes issues when running tests with "python test_xxx.py".

Relative path -> Absolute path.

### CODE REVIEW

**Review by DavidLP — APPROVED** [review]
Thought that was working already

**Comment by laborleben** [comment]
Xcode got stuck. Let's wait...

**Comment by laborleben** [comment]
Unmerged... something went wrong. Reopen.

**Comment by DavidLP** [comment]
What is this "something"?

**Comment by laborleben** [comment]
The message was:
```This pull request is closed, but the fix-path branch has unmerged commits.```
And nothing was merged. Even though it was rebased on top of development. No conflicts.

**Comment by DavidLP** [comment]
Maybe you clicked `close` instead of `merge`? At least the history suggests that.

**Comment by laborleben** [comment]
Hmmm, I don't know. But I did not "close and comment". That's for sure.

**Pull request merged**
